### ISSUE TITLE
Too few arguments to function pepdo::fetchAll() www/lib/pdosql.cls.php on line 32 and exactly 3 expected in 

### ISSUE THREAD

**Issue by yujiaao** [hainuo/phpems47#3]
Mac OS, nginx 1.12.1,  php7.1

Fatal error: Uncaught ArgumentCountError: Too few arguments to function pepdo::fetchAll(), 1 passed in /Users/xwx/Sites/phpems47/www/lib/pdosql.cls.php on line 32 and exactly 3 expected in /Users/xwx/Sites/phpems47/www/lib/pepdo.cls.php:56 Stack trace: #0 /Users/xwx/Sites/phpems47/www/lib/pdosql.cls.php(32): pepdo->fetchAll(Array) #1 /Users/xwx/Sites/phpems47/www/lib/pdosql.cls.php(317): pdosql->_makeDefaultInsertArgs(Array, Array) #2 /Users/xwx/Sites/phpems47/www/lib/session.cls.php(32): pdosql->makeInsert(Array) #3 /Users/xwx/Sites/phpems47/www/lib/session.cls.php(17): session->getSessionId() #4 /Users/xwx/Sites/phpems47/www/lib/init.cls.php(82): session->__construct(Object(ginkgo)) #5 /Users/xwx/Sites/phpems47/www/app/content/app.php(19): ginkgo->make('session') #6 /Users/xwx/Sites/phpems47/www/lib/init.cls.php(128): app->__construct(Object(ginkgo)) #7 /Users/xwx/Sites/phpems47/www/index.php(8): ginkgo->run() #8 {main} thrown in /Users/xwx/Sites/phpems47/www/lib/pepdo.cls.php on line 56

**Comment by yujiaao** [comment]
pepdo.cls.php : 56 

    public function fetchAll($sql, $index, $unserialize)
==>
   public function fetchAll($sql, $index = false,$unserialize = false)

**Comment by yujiaao** [comment]
see pull request `work under php7.1 #4`

**Comment by hainuo** [comment]
merged
